# dictioanry to define the column we will use in at least one hypothesis
columns_interest = {
        'age': 'continuous',
        'bmi': 'continuous',
        'ess_0900': 'continuous',
        'gender': 'binary',
        'map_0100': {
                    0: "Never",
                    1: "Rarely",
                    2: "Sometimes",
                    3: "Frequently",
                    4: "Always",
                    -55: "Don't Know"
                },
        'map_0300':{
                    0: "Never",
                    1: "Rarely",
                    2: "Sometimes",
                    3: "Frequently",
                    4: "Always",
                    -55: "Don't Know"
                },
        'map_0600': {
                    0: "Never",
                    1: "Rarely",
                    2: "Sometimes",
                    3: "Frequently",
                    4: "Always",
                    -55: "Don't Know"
                },
        'mdhx_sleep_problem_0': 'binary',
        'mdhx_sleep_problem_1': 'binary',
        'mdhx_sleep_problem_2': 'binary',
        'mdhx_sleep_problem_3': 'binary',
        'mdhx_sleep_problem_4': 'binary',
        'mdhx_sleep_problem_5': 'binary',
        'mdhx_sleep_problem_6': 'binary',
        'mdhx_sleep_problem_7': 'binary',
        'mdhx_sleep_problem_8': 'binary',
        'mdhx_sleep_problem_9': 'binary',
        'mdhx_sleep_problem_10': 'binary',
        'mdhx_sleep_problem_11': 'binary',
        'mdhx_sleep_problem_12': 'binary',
        'mdhx_sleep_problem_13': 'binary',
        'mdhx_sleep_problem_14': 'binary',
        'par_0205': 'continuous',
        'par_0305': 'continuous',
        'par_0505': 'continuous',
        # 'par_0510',
        'par_0605': 'continuous',
        'par_1005': 'continuous',
        'race':{
                0: "European",
                1: "Middle Eastern",
                2: "N. African",
                3: "Other White/European",
                4: "Asian Indian",
                5: "Chinese",
                6: "Filipino",
                7: "Japanese",
                8: "Korean",
                9: "Vietnamese",
                10: "Other Asian",
                11: "Native Hawaiian",
                12: "Guamanian or Chamorro",
                13: "Samoan",
                14: "Other Pacific Islander"
            },
        'rls_probability': 'continuous',
        'map_index_1': 'continuous',
        'map_index_4': 'continuous',
        'isi_score': 'continuous',
        }




def columns_dictionary() -> dict[str, str]:
    columns_names = {
        'gender': 'Gender',  # 1=female, 0=male
        'bmi': 'BMI',
        'race': 'Race',
        'ess_0900': 'ESS Score',
        'score': 'MAP Score',
        'rls_probability': 'RLS Probability',
        'par_0205': 'Sleep Walking',
        'par_0305': 'Sleep Eating',
        'par_0505': 'Acting out dreams',
        'par_0605': 'Violent Behaviour Sleep',
        'par_1005': 'Sex No Memory',
        'map_0100': 'Loud Snore',
        'map_0300': 'Snorting/Gasping',
        'map_0600': 'Breathing Stops',
        'map_index_1': 'Apnea Score',
        'map_index_4': 'Narcolepsy Like Symptoms Score',
        'mdhx_sleep_problem_0': 'No sleep problem',
        'mdhx_sleep_problem_1': 'Snoring',
        'mdhx_sleep_problem_2': 'Breath Stops night time',
        'mdhx_sleep_problem_3': 'Sleepiness Day',
        'mdhx_sleep_problem_4': 'Unrefreshing sleep',
        'mdhx_sleep_problem_5': 'Difficulty Sleep Onset',
        'mdhx_sleep_problem_6': 'Difficulty Staying Asleep',
        'mdhx_sleep_problem_7': 'Difficulty Sleep Schedule',
        'mdhx_sleep_problem_8': 'Sleep Behaviour',
        'mdhx_sleep_problem_9': 'Nightmares',
        'mdhx_sleep_problem_10': 'Act out dreams',
        'mdhx_sleep_problem_11': 'Restless legs',
        'mdhx_sleep_problem_12': 'Weakness Muscle',
        'mdhx_sleep_problem_13': 'Other Sleep Problem',
        'mdhx_sleep_problem_14': 'Bruxism',
        'isi_score': 'ISI Score',
    }
    return columns_names


col_ehr = {
    'Days the Person Has Had Long COVID': 'continuous',
    'Headaches': 'continuous',
    'Nasal Congestion': 'continuous',
    'Fatigue': 'continuous',
    'Brain fog': 'continuous',
    'Unrefreshing sleep': 'continuous',
    'Insomnia': 'continuous',
    'Lethargy': 'continuous',
    'Post-exertional Malaise': 'continuous',
    'Change in Smell': 'continuous',
    'Change in Taste': 'continuous',
    'Anxiety/Depression': 'continuous',
    'Cough': 'continuous',
    'Shortness of Breath': 'continuous',
    'Lightheadedness': 'continuous',
    'GI Symptoms': 'continuous',
    'Functional Satus': 'continuous',
    'Cortisol Levels': 'continuous',
    'Time Cortisol Collected': 'continuous',
    'Number of COVID-19 symptoms': 'continuous',
    'Preexisting sleep symptoms - binary': 'binary',
    'Hospitalized (no = 0, yes = 1)': 'binary',
    'COVID-19 vaccination status (no = 0, yes = 1), (2 doses of the vaccine)': 'binary',
    }